apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: secretworld-app-clone-
  labels:
    tekton.dev/pipeline: secretworld-app-clone
spec:
  serviceAccountName: github-bot
  pipelineRef:
    name: secretworld-app-clone
  params:
    - name: private-github-repo-url
      value: https://github.com/codequester/tekton-tutorial-greeter.git
  workspaces:
    - name: source
      persistentVolumeClaim:
        claimName: tekton-tutorial-sources
